config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  
  
  get 'sessions/new'
  resources :articles do
    resources :comments
  end

  resources :users

  get 'login', to: 'sessions#new', as: 'login'
  
  resources :sessions

  get 'welcome/index'

  root 'articles#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

# This is the Article model
class Article < ApplicationRecord
  has_many(:comments, dependent: :destroy)
  validates(:title,
            presence: true,
            length: { minimum: 5 })
end

app/models/budget_detail.rb
class BudgetDetail < ApplicationRecord
  belongs_to :budget_plan
  belongs_to :category
end

app/models/budget_plan.rb
class BudgetPlan < ApplicationRecord
  belongs_to :user
  has_many :budget_details, dependent: :destroy
  has_many :expenses, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :budget_details
  has_many :expenses
end

app/models/comment.rb
# frozen_string_literal: true

# This model handles commenting currently for articles but can be added to
# to any item like spictures, products and videos.
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/expense.rb
# frozen_string_literal: true

# This is the Expense model
class Expense < ApplicationRecord
  belongs_to :budget_plan
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  has_many :budget_plans, dependent: :destroy
  has_many :budget_details, through: :budget_plans
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  def index
    # re-ordering aricles based on create at date, with most recently
    # created articles at the top
    @articles = Article.all.order(created_at: :desc)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      # rails calls the show action
      redirect_to @article
      # render plain: params[:article].inspect
    else
      render 'edit'
    end
  end

  # if nothing defined in create method then by default rails will
  # return response 204 no content
  def create
    puts " ##########################  #{params[:article].inspect}"

    # @article = Article.new(params[:article])
    @article = Article.new(article_params)

    if @article.save
      # rails calls the show action
      redirect_to @article
      # render plain: params[:article].inspect
    else
      render 'new'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    # rails calls the show action
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def add
  end

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  # If accessing from outside this domain, nullify the session
  # This allows for outside API access while preventing CSRF attacks,
  # but you'll have to authenticate your user separately
  # protect_from_forgery with: :null_session

  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = BlogSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue => e
    raise e unless Rails.env.development?
    handle_error_in_development e
  end

  private

  # Handle form data, JSON body, or a blank value
  def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      if ambiguous_param.present?
        ensure_hash(JSON.parse(ambiguous_param))
      else
        {}
      end
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { error: { message: e.message, backtrace: e.backtrace }, data: {} }, status: 500
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create

    @user = User.find_by(user_name: params[:user_name])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to articles_path notice: 'Logged in!'
      puts ">>>>>>>>>>>>>>>>>>>> logged in <>>>>>>>>>>>>>>>"
      puts @user.error.messages if @user.errors.any?
    else
      @name = params[:user_name]
      @password = params[:password]
      flash[:notice] = 'Oops that is not what we were expecting.'
      render 'sessions/new'
    end
  end

  def index
    flash[:notice] = nil
    render 'sessions/new'
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    redirect_to articles_path
  end

  def create

        @user = User.new(article_params)
        puts "**********************************************************"
        puts "created new user" 
        puts Time.now
        puts "**********************************************************"

        if @user.save
          redirect_to @user
        else
          flash[:notice] = "Not a valid user profile sorry you got to do better than that."
          render 'new'
        end
  end

  private

  def article_params
    params.require(:user).permit(:f_name, :l_name, :email, :user_name, :password, :password_confirmation)
  end

#     users GET    /users(.:format)                                                                         users#index
#         POST   /users(.:format)                                                                         users#create
# new_user GET    /users/new(.:format)                                                                     users#new
# edit_user GET    /users/:id/edit(.:format)                                                                users#edit
# user GET    /users/:id(.:format)                                                                     users#show
#     PATCH  /users/:id(.:format)                                                                     users#update
#     PUT    /users/:id(.:format)                                                                     users#update
#     DELETE /users/:id(.:format)                                                                     users#destroy
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<!-- local: true sets the page for full redirect by default
forms use ajax unless disabled like so-->
<%= form_with model: @article, local: true do |f|%>  
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@article.errors.count, 'error') %> prohibited this article
      from being saved:
    </h2>
    <ul>
      <% @article.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :text %><br>
  <%= f.text_area :text %>
</p>
<p>
  <%= f.submit %>
</p>
<%end%>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

<%= link_to 'Show Articles', articles_path %>

app/views/articles/index.html.erb
<p style="color: green"><%=flash[:notice]%></p>
<% if current_user %>
  <!-- If you're logged in then you can create an article and you 
       also log out -->
  <p><%= link_to 'New article', new_article_path %>&nbsp&nbsp&nbsp&nbsp
  <em>Logged in as <%= current_user.user_name %></em></p>
  <%= link_to 'Log Out', session_path("current"), method: "delete" %>
<% else%>
  <!-- Only Logged in users can edit and create articles -->
  <%= link_to 'Sign up', new_user_path %>&nbsp&nbsp
  <!-- this rout was remapped in routes.rb from new_session_path to this 
       now displays in browser as /login -->
  <%= link_to 'Log In', login_path %> 
<% end %>

<div id="resp-table">

  <div id=“resp-table-caption”>
    <h2>Current Articles</h2><br><br>
  </div>
  <div id=“resp-table-header”>
    
    <div class=“table-header-cell”>
       <%# <h4>Title</h4> %>
    </div>

    <div class=“table-header-cell”>
      <%# <h4>Text</h4> %>
    </div>

  </div>
  <div id=“resp-table-body”>
    

      <% @articles.each do |article|%>
      <div class=“resp-table-row”>
        <div class=“table-body-cell”><mark class="article-title"><%= article.title %></mark></div>
        <div class=“table-body-cell”><%= article.text %><br>
        <div class=“table-body-cell”><i>Created on <%= article.created_at %></i><br><br>
            <%= link_to 'View', article_path(article) %>&nbsp &nbsp
            <% if current_user %>
            <%= link_to 'Edit', edit_article_path(article) %>&nbsp &nbsp
            <%= link_to 'Delete', article_path(article), 
                method: :delete,
                data: {confirm: 'Are you certain?' } %><br><br>
            <% end %>
        </div>  
        
      </div>
      <% end %>
  </div>

  
<div>

app/views/articles/new.html.erb
<h1>New article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Show all', articles_path %>

app/views/articles/show.html.erb
<p>
  <h3><%= @article.title %></h3>
</p>

<p>
  <%= @article.text %><br><br>
  <%= link_to 'Edit', edit_article_path(@article) %>&nbsp&nbsp
  <%= link_to 'Delete', article_path(@article), 
                method: :delete,
                data: {confirm: 'Are you certain?' } %>
</p>

<h4>Comments:</h4>
<%= render @article.comments %>

<h5>Add a comment:</h5>
<%= render 'comments/form' %>

<br>
<%= link_to 'Show All', articles_path %>

app/views/comments/_comment.html.erb
<p><%=  comment.commenter %> 
<i>says...
<%= comment.body %></i></p>
<%= link_to 'Remove comment', [comment.article, comment],
            method: :delete,
            data: {confirm: 'Are you sure?'} %><br>       

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |f_com|  %>
<p>
  <%= f_com.label :commenter %><br>
  <%= f_com.text_field :commenter %><br>
</p>
<p>
  <%= f_com.label :body %><br>
  <%= f_com.text_area(:body, style: 'width: 500px; height: 200px') %><br>
</p>
<p>
  <%= f_com.submit %>
</p>
<% end %>

app/views/comments/add.html.erb
<h1>Comments#add</h1>
<p>Find me in app/views/comments/add.html.erb</p>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <script src="https://unpkg.com/react@16/umd/react.development.js" crossorigin></script>
    <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js" crossorigin></script> 
    <script javascript_pack_tag src="like_button.js" crossorigin></script> -->

    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
      h1 {
        color: red;
      }
       /* add inline styles here  */
    </style>
  </head>

  <body id="home" class="open-left" style="margin: 0 10%;"> <!--  id="home" class="open-left"> -->
 <!--<div id="offcanvas-left" class="hide">
    <ul>
      <li><a href="#">Create Article</a></li>
      <li><a href="#">Add comment</a></li>
      <li><a href="#">Go home</a></li>
    </ul>
  </div>
  <div class="togglebar">
    <div class="toggle" onclick="toggleLeft()">
      <i class="fa fa-bars"></i>
    </div>
  </div> -->
  <div >
    <%= yield %>
  </div>
  </body>
</html>

app/views/users/new.html.erb
<h1>Create User</h1>
<!-- local: true sets the page for full redirect by default
forms use ajax unless disabled like so-->
<p style="color: green"><%= flash[:notice] %></p>
<%if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, 'error') %> prohibited this user
      from being created:
    </h2>
    <ul>
      <% @user.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @user, local: true do |f|%> 
    <div>
      <%= f.label :"first name" %><br>
      <%= f.text_field :f_name %>
    </div>
   <p>
      <%= f.label :"last name" %><br>
      <%= f.text_field :l_name %>
    </p>
    <p>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :"user name" %><br>
      <%= f.text_field :user_name %>
    </p>
    <p>
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :"confirm password" %><br>
      <%= f.password_field :password_confirmation %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<%end%> 

app/views/users/show.html.erb
<h1>Your profile was created<h1>

<p>
  <h3><%= "#{@user.f_name} #{@user.l_name}" %></h3>
</p>

app/views/welcome/index.html.erb
<h1>Hello Railsssss!</h1>